apiVersion: v1
kind: Service
metadata:
  name: msgapp-backend
  labels:
    app: msgapp
    component: backend
spec:
  type: {{ .Values.backend.service.type }}
  # Enable sticky sessions for Socket.io connections
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: msgapp
    component: backend
