{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: msgapp-mongodb
  labels:
    app: msgapp
    component: database
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    app: msgapp
    component: database
{{- end }}
