apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: msgapp-rabbitmq
  labels:
    app: msgapp
    component: rabbitmq
spec:
  serviceName: msgapp-rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: msgapp
      component: rabbitmq
  template:
    metadata:
      labels:
        app: msgapp
        component: rabbitmq
        azure.workload.identity/use: "true"
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management-alpine
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.rabbitmq.username }}"
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: msgapp-synced-secrets
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_DEFAULT_VHOST
              value: "/"
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - ping
            initialDelaySeconds: 180
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - check_port_connectivity
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 20
            failureThreshold: 5
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: msgapp-azure-keyvault
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
