apiVersion: v1
kind: Service
metadata:
  name: msgapp-redis
  labels:
    app: msgapp
    component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: msgapp
    component: redis
