apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: msgapp-vault-bridge
spec:
  provider: azure
  parameters:
    usePodIdentity: "false" # We will use workload identity or managed identity
    useVMManagedIdentity: "true" 
    userAssignedIdentityID: "" # To be filled in production
    keyvaultName: {{ .Values.azure.keyvaultName | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: msgapp-jwt-secret
          objectType: secret
        - |
          objectName: msgapp-rabbitmq-password
          objectType: secret
  secretObjects:
    - secretName: msgapp-synced-secrets
      type: Opaque
      data:
        - objectName: msgapp-jwt-secret
          key: JWT_SECRET
        - objectName: msgapp-rabbitmq-password
          key: RABBITMQ_PASSWORD
